#
# Automatically generated file. DO NOT MODIFY
#

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/daisy

PRODUCT_COPY_FILES += \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Bluetooth_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_General_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_General_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Global_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Global_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Handset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Handset_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Hdmi_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Headset_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Headset_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_Speaker_cal.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_Speaker_cal.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/QRD/QRD_workspaceFile.qwsp:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/QRD/QRD_workspaceFile.qwsp \
    vendor/xiaomi/daisy/proprietary/vendor/etc/acdbdata/adsp_avs_config.acdb:$(TARGET_COPY_OUT_VENDOR)/etc/acdbdata/adsp_avs_config.acdb \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/camera_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/camera_config.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/csidtg_camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_camera.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/csidtg_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/csidtg_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_imx486_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_imx486_ofilm_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_imx486_ofilm_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_imx486_ofilm_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_imx486_ofilm_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_imx486_ofilm_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov12a10_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov12a10_sunny_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov12a10_sunny_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov12a10_sunny_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov12a10_sunny_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov12a10_sunny_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_ofilm_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_ofilm_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_ofilm_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_ofilm_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_ofilm_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_qtech_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_qtech_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_qtech_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_qtech_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_ov5675_qtech_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_ov5675_qtech_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_ofilm_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_ofilm_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_ofilm_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_ofilm_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_ofilm_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_ofilm_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_sunny_chromatix.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_sunny_chromatix.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_sunny_chromatix_cn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_sunny_chromatix_cn.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/camera/sakura_s5k5e8_sunny_chromatix_india.xml:$(TARGET_COPY_OUT_VENDOR)/etc/camera/sakura_s5k5e8_sunny_chromatix_india.xml \
    vendor/xiaomi/daisy/proprietary/vendor/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.gatekeeper@1.0-service-qti.rc \
    vendor/xiaomi/daisy/proprietary/vendor/etc/init/android.hardware.keymaster@3.0-service-qti.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.keymaster@3.0-service-qti.rc \
    vendor/xiaomi/daisy/proprietary/vendor/etc/sensors/sensor_def_qcomdev.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/sensor_def_qcomdev.conf \
    vendor/xiaomi/daisy/proprietary/vendor/firmware/goodix_firmware.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/goodix_firmware.bin

PRODUCT_PACKAGES += \
    libactuator_sakura_dw9714v_ofilm \
    libactuator_sakura_dw9714v_sunny \
    libarcsoft_high_dynamic_range \
    libcapiv2svacnn \
    libcapiv2vop \
    libchromaflash \
    libchromatix_ov12a10_sunny_sakura_4k_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_4k_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_4k_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_4k_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_common \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_hht_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_liveshot \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_preview \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_snapshot \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_snapshot_hht \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_video \
    libchromatix_ov12a10_sunny_sakura_cn_cpp_video_4k \
    libchromatix_ov12a10_sunny_sakura_cn_default_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_default_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_120_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_60_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_cn_hfr_90_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_postproc \
    libchromatix_ov12a10_sunny_sakura_cn_preview \
    libchromatix_ov12a10_sunny_sakura_cn_snapshot \
    libchromatix_ov12a10_sunny_sakura_cn_video_4k \
    libchromatix_ov12a10_sunny_sakura_cn_zsl_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_cn_zsl_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_common \
    libchromatix_ov12a10_sunny_sakura_cpp_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_cpp_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_cpp_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_cpp_hht_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_cpp_liveshot \
    libchromatix_ov12a10_sunny_sakura_cpp_preview \
    libchromatix_ov12a10_sunny_sakura_cpp_snapshot \
    libchromatix_ov12a10_sunny_sakura_cpp_snapshot_hht \
    libchromatix_ov12a10_sunny_sakura_cpp_video \
    libchromatix_ov12a10_sunny_sakura_cpp_video_4k \
    libchromatix_ov12a10_sunny_sakura_default_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_default_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_hfr_120_dw9763 \
    libchromatix_ov12a10_sunny_sakura_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_hfr_60_dw9763 \
    libchromatix_ov12a10_sunny_sakura_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_hfr_90_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_4k_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_4k_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_common \
    libchromatix_ov12a10_sunny_sakura_india_cpp_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_india_cpp_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_india_cpp_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_india_cpp_liveshot \
    libchromatix_ov12a10_sunny_sakura_india_cpp_preview \
    libchromatix_ov12a10_sunny_sakura_india_cpp_snapshot \
    libchromatix_ov12a10_sunny_sakura_india_cpp_snapshot_hht \
    libchromatix_ov12a10_sunny_sakura_india_cpp_video \
    libchromatix_ov12a10_sunny_sakura_india_cpp_video_4k \
    libchromatix_ov12a10_sunny_sakura_india_default_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_default_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_120 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_120_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_60 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_60_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_90 \
    libchromatix_ov12a10_sunny_sakura_india_hfr_90_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_postproc \
    libchromatix_ov12a10_sunny_sakura_india_preview \
    libchromatix_ov12a10_sunny_sakura_india_snapshot \
    libchromatix_ov12a10_sunny_sakura_india_video_4k \
    libchromatix_ov12a10_sunny_sakura_india_zsl_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_india_zsl_video_dw9763 \
    libchromatix_ov12a10_sunny_sakura_postproc \
    libchromatix_ov12a10_sunny_sakura_preview \
    libchromatix_ov12a10_sunny_sakura_snapshot \
    libchromatix_ov12a10_sunny_sakura_video_4k \
    libchromatix_ov12a10_sunny_sakura_zsl_preview_dw9763 \
    libchromatix_ov12a10_sunny_sakura_zsl_video_dw9763 \
    libchromatix_sakura_cn_imx486_ofilm_common \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hfr_120 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hfr_60 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hfr_90 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hht_hfr_120 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hht_hfr_60 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_hht_hfr_90 \
    libchromatix_sakura_cn_imx486_ofilm_cpp_liveshot \
    libchromatix_sakura_cn_imx486_ofilm_cpp_preview \
    libchromatix_sakura_cn_imx486_ofilm_cpp_snapshot \
    libchromatix_sakura_cn_imx486_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_cn_imx486_ofilm_cpp_video \
    libchromatix_sakura_cn_imx486_ofilm_default_preview_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_default_video \
    libchromatix_sakura_cn_imx486_ofilm_default_video_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_hfr_120 \
    libchromatix_sakura_cn_imx486_ofilm_hfr_120_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_hfr_60 \
    libchromatix_sakura_cn_imx486_ofilm_hfr_60_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_hfr_90 \
    libchromatix_sakura_cn_imx486_ofilm_hfr_90_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_postproc \
    libchromatix_sakura_cn_imx486_ofilm_preview \
    libchromatix_sakura_cn_imx486_ofilm_snapshot \
    libchromatix_sakura_cn_imx486_ofilm_zsl_preview_dw9714v \
    libchromatix_sakura_cn_imx486_ofilm_zsl_video_dw9714v \
    libchromatix_sakura_cn_ov5675_ofilm_common \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hfr_120 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hfr_60 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hfr_90 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hht_hfr_120 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hht_hfr_60 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_hht_hfr_90 \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_liveshot \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_preview \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_snapshot \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_cn_ov5675_ofilm_cpp_video \
    libchromatix_sakura_cn_ov5675_ofilm_default_preview_3a \
    libchromatix_sakura_cn_ov5675_ofilm_default_video \
    libchromatix_sakura_cn_ov5675_ofilm_default_video_3a \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_120 \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_120_3a \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_60 \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_60_3a \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_90 \
    libchromatix_sakura_cn_ov5675_ofilm_hfr_90_3a \
    libchromatix_sakura_cn_ov5675_ofilm_liveshot \
    libchromatix_sakura_cn_ov5675_ofilm_postproc \
    libchromatix_sakura_cn_ov5675_ofilm_preview \
    libchromatix_sakura_cn_ov5675_ofilm_snapshot \
    libchromatix_sakura_cn_ov5675_ofilm_zsl_preview_3a \
    libchromatix_sakura_cn_ov5675_ofilm_zsl_video_3a \
    libchromatix_sakura_cn_ov5675_qtech_common \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hfr_120 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hfr_60 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hfr_90 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hht_hfr_120 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hht_hfr_60 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_hht_hfr_90 \
    libchromatix_sakura_cn_ov5675_qtech_cpp_liveshot \
    libchromatix_sakura_cn_ov5675_qtech_cpp_preview \
    libchromatix_sakura_cn_ov5675_qtech_cpp_snapshot \
    libchromatix_sakura_cn_ov5675_qtech_cpp_snapshot_hht \
    libchromatix_sakura_cn_ov5675_qtech_cpp_video \
    libchromatix_sakura_cn_ov5675_qtech_default_preview_3a \
    libchromatix_sakura_cn_ov5675_qtech_default_video \
    libchromatix_sakura_cn_ov5675_qtech_default_video_3a \
    libchromatix_sakura_cn_ov5675_qtech_hfr_120 \
    libchromatix_sakura_cn_ov5675_qtech_hfr_120_3a \
    libchromatix_sakura_cn_ov5675_qtech_hfr_60 \
    libchromatix_sakura_cn_ov5675_qtech_hfr_60_3a \
    libchromatix_sakura_cn_ov5675_qtech_hfr_90 \
    libchromatix_sakura_cn_ov5675_qtech_hfr_90_3a \
    libchromatix_sakura_cn_ov5675_qtech_liveshot \
    libchromatix_sakura_cn_ov5675_qtech_postproc \
    libchromatix_sakura_cn_ov5675_qtech_preview \
    libchromatix_sakura_cn_ov5675_qtech_snapshot \
    libchromatix_sakura_cn_ov5675_qtech_zsl_preview_3a \
    libchromatix_sakura_cn_ov5675_qtech_zsl_video_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_common \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_hfr_120 \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_hfr_60 \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_hfr_90 \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_liveshot \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_preview \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_snapshot \
    libchromatix_sakura_cn_s5k5e8_ofilm_cpp_video \
    libchromatix_sakura_cn_s5k5e8_ofilm_default_preview_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_default_video \
    libchromatix_sakura_cn_s5k5e8_ofilm_default_video_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_120 \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_120_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_60 \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_60_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_90 \
    libchromatix_sakura_cn_s5k5e8_ofilm_hfr_90_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_liveshot \
    libchromatix_sakura_cn_s5k5e8_ofilm_postproc \
    libchromatix_sakura_cn_s5k5e8_ofilm_preview \
    libchromatix_sakura_cn_s5k5e8_ofilm_snapshot \
    libchromatix_sakura_cn_s5k5e8_ofilm_zsl_preview_3a \
    libchromatix_sakura_cn_s5k5e8_ofilm_zsl_video_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_common \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_hfr_120 \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_hfr_60 \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_hfr_90 \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_liveshot \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_preview \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_snapshot \
    libchromatix_sakura_cn_s5k5e8_sunny_cpp_video \
    libchromatix_sakura_cn_s5k5e8_sunny_default_preview_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_default_video \
    libchromatix_sakura_cn_s5k5e8_sunny_default_video_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_120 \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_120_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_60 \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_60_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_90 \
    libchromatix_sakura_cn_s5k5e8_sunny_hfr_90_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_liveshot \
    libchromatix_sakura_cn_s5k5e8_sunny_postproc \
    libchromatix_sakura_cn_s5k5e8_sunny_preview \
    libchromatix_sakura_cn_s5k5e8_sunny_snapshot \
    libchromatix_sakura_cn_s5k5e8_sunny_zsl_preview_3a \
    libchromatix_sakura_cn_s5k5e8_sunny_zsl_video_3a \
    libchromatix_sakura_imx486_ofilm_common \
    libchromatix_sakura_imx486_ofilm_cpp_hfr_120 \
    libchromatix_sakura_imx486_ofilm_cpp_hfr_60 \
    libchromatix_sakura_imx486_ofilm_cpp_hfr_90 \
    libchromatix_sakura_imx486_ofilm_cpp_hht_hfr_120 \
    libchromatix_sakura_imx486_ofilm_cpp_hht_hfr_60 \
    libchromatix_sakura_imx486_ofilm_cpp_hht_hfr_90 \
    libchromatix_sakura_imx486_ofilm_cpp_liveshot \
    libchromatix_sakura_imx486_ofilm_cpp_preview \
    libchromatix_sakura_imx486_ofilm_cpp_snapshot \
    libchromatix_sakura_imx486_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_imx486_ofilm_cpp_video \
    libchromatix_sakura_imx486_ofilm_default_preview_dw9714v \
    libchromatix_sakura_imx486_ofilm_default_video \
    libchromatix_sakura_imx486_ofilm_default_video_dw9714v \
    libchromatix_sakura_imx486_ofilm_hfr_120 \
    libchromatix_sakura_imx486_ofilm_hfr_120_dw9714v \
    libchromatix_sakura_imx486_ofilm_hfr_60 \
    libchromatix_sakura_imx486_ofilm_hfr_60_dw9714v \
    libchromatix_sakura_imx486_ofilm_hfr_90 \
    libchromatix_sakura_imx486_ofilm_hfr_90_dw9714v \
    libchromatix_sakura_imx486_ofilm_postproc \
    libchromatix_sakura_imx486_ofilm_preview \
    libchromatix_sakura_imx486_ofilm_snapshot \
    libchromatix_sakura_imx486_ofilm_zsl_preview_dw9714v \
    libchromatix_sakura_imx486_ofilm_zsl_video_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_common \
    libchromatix_sakura_india_imx486_ofilm_cpp_hfr_120 \
    libchromatix_sakura_india_imx486_ofilm_cpp_hfr_60 \
    libchromatix_sakura_india_imx486_ofilm_cpp_hfr_90 \
    libchromatix_sakura_india_imx486_ofilm_cpp_liveshot \
    libchromatix_sakura_india_imx486_ofilm_cpp_preview \
    libchromatix_sakura_india_imx486_ofilm_cpp_snapshot \
    libchromatix_sakura_india_imx486_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_india_imx486_ofilm_cpp_video \
    libchromatix_sakura_india_imx486_ofilm_default_preview_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_default_video \
    libchromatix_sakura_india_imx486_ofilm_default_video_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_hfr_120 \
    libchromatix_sakura_india_imx486_ofilm_hfr_120_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_hfr_60 \
    libchromatix_sakura_india_imx486_ofilm_hfr_60_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_hfr_90 \
    libchromatix_sakura_india_imx486_ofilm_hfr_90_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_postproc \
    libchromatix_sakura_india_imx486_ofilm_preview \
    libchromatix_sakura_india_imx486_ofilm_snapshot \
    libchromatix_sakura_india_imx486_ofilm_zsl_preview_dw9714v \
    libchromatix_sakura_india_imx486_ofilm_zsl_video_dw9714v \
    libchromatix_sakura_india_ov5675_ofilm_common \
    libchromatix_sakura_india_ov5675_ofilm_cpp_hfr_120 \
    libchromatix_sakura_india_ov5675_ofilm_cpp_hfr_60 \
    libchromatix_sakura_india_ov5675_ofilm_cpp_hfr_90 \
    libchromatix_sakura_india_ov5675_ofilm_cpp_liveshot \
    libchromatix_sakura_india_ov5675_ofilm_cpp_preview \
    libchromatix_sakura_india_ov5675_ofilm_cpp_snapshot \
    libchromatix_sakura_india_ov5675_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_india_ov5675_ofilm_cpp_video \
    libchromatix_sakura_india_ov5675_ofilm_default_preview_3a \
    libchromatix_sakura_india_ov5675_ofilm_default_video \
    libchromatix_sakura_india_ov5675_ofilm_default_video_3a \
    libchromatix_sakura_india_ov5675_ofilm_hfr_120 \
    libchromatix_sakura_india_ov5675_ofilm_hfr_120_3a \
    libchromatix_sakura_india_ov5675_ofilm_hfr_60 \
    libchromatix_sakura_india_ov5675_ofilm_hfr_60_3a \
    libchromatix_sakura_india_ov5675_ofilm_hfr_90 \
    libchromatix_sakura_india_ov5675_ofilm_hfr_90_3a \
    libchromatix_sakura_india_ov5675_ofilm_liveshot \
    libchromatix_sakura_india_ov5675_ofilm_postproc \
    libchromatix_sakura_india_ov5675_ofilm_preview \
    libchromatix_sakura_india_ov5675_ofilm_snapshot \
    libchromatix_sakura_india_ov5675_ofilm_zsl_preview_3a \
    libchromatix_sakura_india_ov5675_ofilm_zsl_video_3a \
    libchromatix_sakura_india_ov5675_qtech_common \
    libchromatix_sakura_india_ov5675_qtech_cpp_hfr_120 \
    libchromatix_sakura_india_ov5675_qtech_cpp_hfr_60 \
    libchromatix_sakura_india_ov5675_qtech_cpp_hfr_90 \
    libchromatix_sakura_india_ov5675_qtech_cpp_liveshot \
    libchromatix_sakura_india_ov5675_qtech_cpp_preview \
    libchromatix_sakura_india_ov5675_qtech_cpp_snapshot \
    libchromatix_sakura_india_ov5675_qtech_cpp_snapshot_hht \
    libchromatix_sakura_india_ov5675_qtech_cpp_video \
    libchromatix_sakura_india_ov5675_qtech_default_preview_3a \
    libchromatix_sakura_india_ov5675_qtech_default_video \
    libchromatix_sakura_india_ov5675_qtech_default_video_3a \
    libchromatix_sakura_india_ov5675_qtech_hfr_120 \
    libchromatix_sakura_india_ov5675_qtech_hfr_120_3a \
    libchromatix_sakura_india_ov5675_qtech_hfr_60 \
    libchromatix_sakura_india_ov5675_qtech_hfr_60_3a \
    libchromatix_sakura_india_ov5675_qtech_hfr_90 \
    libchromatix_sakura_india_ov5675_qtech_hfr_90_3a \
    libchromatix_sakura_india_ov5675_qtech_liveshot \
    libchromatix_sakura_india_ov5675_qtech_postproc \
    libchromatix_sakura_india_ov5675_qtech_preview \
    libchromatix_sakura_india_ov5675_qtech_snapshot \
    libchromatix_sakura_india_ov5675_qtech_zsl_preview_3a \
    libchromatix_sakura_india_ov5675_qtech_zsl_video_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_common \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_hfr_120 \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_hfr_60 \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_hfr_90 \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_liveshot \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_preview \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_snapshot \
    libchromatix_sakura_india_s5k5e8_ofilm_cpp_video \
    libchromatix_sakura_india_s5k5e8_ofilm_default_preview_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_default_video \
    libchromatix_sakura_india_s5k5e8_ofilm_default_video_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_120 \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_120_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_60 \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_60_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_90 \
    libchromatix_sakura_india_s5k5e8_ofilm_hfr_90_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_liveshot \
    libchromatix_sakura_india_s5k5e8_ofilm_postproc \
    libchromatix_sakura_india_s5k5e8_ofilm_preview \
    libchromatix_sakura_india_s5k5e8_ofilm_snapshot \
    libchromatix_sakura_india_s5k5e8_ofilm_zsl_preview_3a \
    libchromatix_sakura_india_s5k5e8_ofilm_zsl_video_3a \
    libchromatix_sakura_india_s5k5e8_sunny_common \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_hfr_120 \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_hfr_60 \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_hfr_90 \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_liveshot \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_preview \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_snapshot \
    libchromatix_sakura_india_s5k5e8_sunny_cpp_video \
    libchromatix_sakura_india_s5k5e8_sunny_default_preview_3a \
    libchromatix_sakura_india_s5k5e8_sunny_default_video \
    libchromatix_sakura_india_s5k5e8_sunny_default_video_3a \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_120 \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_120_3a \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_60 \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_60_3a \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_90 \
    libchromatix_sakura_india_s5k5e8_sunny_hfr_90_3a \
    libchromatix_sakura_india_s5k5e8_sunny_liveshot \
    libchromatix_sakura_india_s5k5e8_sunny_postproc \
    libchromatix_sakura_india_s5k5e8_sunny_preview \
    libchromatix_sakura_india_s5k5e8_sunny_snapshot \
    libchromatix_sakura_india_s5k5e8_sunny_zsl_preview_3a \
    libchromatix_sakura_india_s5k5e8_sunny_zsl_video_3a \
    libchromatix_sakura_ov5675_ofilm_common \
    libchromatix_sakura_ov5675_ofilm_cpp_hfr_120 \
    libchromatix_sakura_ov5675_ofilm_cpp_hfr_60 \
    libchromatix_sakura_ov5675_ofilm_cpp_hfr_90 \
    libchromatix_sakura_ov5675_ofilm_cpp_hht_hfr_120 \
    libchromatix_sakura_ov5675_ofilm_cpp_hht_hfr_60 \
    libchromatix_sakura_ov5675_ofilm_cpp_hht_hfr_90 \
    libchromatix_sakura_ov5675_ofilm_cpp_liveshot \
    libchromatix_sakura_ov5675_ofilm_cpp_preview \
    libchromatix_sakura_ov5675_ofilm_cpp_snapshot \
    libchromatix_sakura_ov5675_ofilm_cpp_snapshot_hht \
    libchromatix_sakura_ov5675_ofilm_cpp_video \
    libchromatix_sakura_ov5675_ofilm_default_preview_3a \
    libchromatix_sakura_ov5675_ofilm_default_video \
    libchromatix_sakura_ov5675_ofilm_default_video_3a \
    libchromatix_sakura_ov5675_ofilm_hfr_120 \
    libchromatix_sakura_ov5675_ofilm_hfr_120_3a \
    libchromatix_sakura_ov5675_ofilm_hfr_60 \
    libchromatix_sakura_ov5675_ofilm_hfr_60_3a \
    libchromatix_sakura_ov5675_ofilm_hfr_90 \
    libchromatix_sakura_ov5675_ofilm_hfr_90_3a \
    libchromatix_sakura_ov5675_ofilm_liveshot \
    libchromatix_sakura_ov5675_ofilm_postproc \
    libchromatix_sakura_ov5675_ofilm_preview \
    libchromatix_sakura_ov5675_ofilm_snapshot \
    libchromatix_sakura_ov5675_ofilm_zsl_preview_3a \
    libchromatix_sakura_ov5675_ofilm_zsl_video_3a \
    libchromatix_sakura_ov5675_qtech_common \
    libchromatix_sakura_ov5675_qtech_cpp_hfr_120 \
    libchromatix_sakura_ov5675_qtech_cpp_hfr_60 \
    libchromatix_sakura_ov5675_qtech_cpp_hfr_90 \
    libchromatix_sakura_ov5675_qtech_cpp_hht_hfr_120 \
    libchromatix_sakura_ov5675_qtech_cpp_hht_hfr_60 \
    libchromatix_sakura_ov5675_qtech_cpp_hht_hfr_90 \
    libchromatix_sakura_ov5675_qtech_cpp_liveshot \
    libchromatix_sakura_ov5675_qtech_cpp_preview \
    libchromatix_sakura_ov5675_qtech_cpp_snapshot \
    libchromatix_sakura_ov5675_qtech_cpp_snapshot_hht \
    libchromatix_sakura_ov5675_qtech_cpp_video \
    libchromatix_sakura_ov5675_qtech_default_preview_3a \
    libchromatix_sakura_ov5675_qtech_default_video \
    libchromatix_sakura_ov5675_qtech_default_video_3a \
    libchromatix_sakura_ov5675_qtech_hfr_120 \
    libchromatix_sakura_ov5675_qtech_hfr_120_3a \
    libchromatix_sakura_ov5675_qtech_hfr_60 \
    libchromatix_sakura_ov5675_qtech_hfr_60_3a \
    libchromatix_sakura_ov5675_qtech_hfr_90 \
    libchromatix_sakura_ov5675_qtech_hfr_90_3a \
    libchromatix_sakura_ov5675_qtech_liveshot \
    libchromatix_sakura_ov5675_qtech_postproc \
    libchromatix_sakura_ov5675_qtech_preview \
    libchromatix_sakura_ov5675_qtech_snapshot \
    libchromatix_sakura_ov5675_qtech_zsl_preview_3a \
    libchromatix_sakura_ov5675_qtech_zsl_video_3a \
    libchromatix_sakura_s5k5e8_ofilm_common \
    libchromatix_sakura_s5k5e8_ofilm_cpp_hfr_120 \
    libchromatix_sakura_s5k5e8_ofilm_cpp_hfr_60 \
    libchromatix_sakura_s5k5e8_ofilm_cpp_hfr_90 \
    libchromatix_sakura_s5k5e8_ofilm_cpp_liveshot \
    libchromatix_sakura_s5k5e8_ofilm_cpp_preview \
    libchromatix_sakura_s5k5e8_ofilm_cpp_snapshot \
    libchromatix_sakura_s5k5e8_ofilm_cpp_video \
    libchromatix_sakura_s5k5e8_ofilm_default_preview_3a \
    libchromatix_sakura_s5k5e8_ofilm_default_video \
    libchromatix_sakura_s5k5e8_ofilm_default_video_3a \
    libchromatix_sakura_s5k5e8_ofilm_hfr_120 \
    libchromatix_sakura_s5k5e8_ofilm_hfr_120_3a \
    libchromatix_sakura_s5k5e8_ofilm_hfr_60 \
    libchromatix_sakura_s5k5e8_ofilm_hfr_60_3a \
    libchromatix_sakura_s5k5e8_ofilm_hfr_90 \
    libchromatix_sakura_s5k5e8_ofilm_hfr_90_3a \
    libchromatix_sakura_s5k5e8_ofilm_liveshot \
    libchromatix_sakura_s5k5e8_ofilm_postproc \
    libchromatix_sakura_s5k5e8_ofilm_preview \
    libchromatix_sakura_s5k5e8_ofilm_snapshot \
    libchromatix_sakura_s5k5e8_ofilm_zsl_preview_3a \
    libchromatix_sakura_s5k5e8_ofilm_zsl_video_3a \
    libchromatix_sakura_s5k5e8_sunny_common \
    libchromatix_sakura_s5k5e8_sunny_cpp_hfr_120 \
    libchromatix_sakura_s5k5e8_sunny_cpp_hfr_60 \
    libchromatix_sakura_s5k5e8_sunny_cpp_hfr_90 \
    libchromatix_sakura_s5k5e8_sunny_cpp_liveshot \
    libchromatix_sakura_s5k5e8_sunny_cpp_preview \
    libchromatix_sakura_s5k5e8_sunny_cpp_snapshot \
    libchromatix_sakura_s5k5e8_sunny_cpp_video \
    libchromatix_sakura_s5k5e8_sunny_default_preview_3a \
    libchromatix_sakura_s5k5e8_sunny_default_video \
    libchromatix_sakura_s5k5e8_sunny_default_video_3a \
    libchromatix_sakura_s5k5e8_sunny_hfr_120 \
    libchromatix_sakura_s5k5e8_sunny_hfr_120_3a \
    libchromatix_sakura_s5k5e8_sunny_hfr_60 \
    libchromatix_sakura_s5k5e8_sunny_hfr_60_3a \
    libchromatix_sakura_s5k5e8_sunny_hfr_90 \
    libchromatix_sakura_s5k5e8_sunny_hfr_90_3a \
    libchromatix_sakura_s5k5e8_sunny_liveshot \
    libchromatix_sakura_s5k5e8_sunny_postproc \
    libchromatix_sakura_s5k5e8_sunny_preview \
    libchromatix_sakura_s5k5e8_sunny_snapshot \
    libchromatix_sakura_s5k5e8_sunny_zsl_preview_3a \
    libchromatix_sakura_s5k5e8_sunny_zsl_video_3a \
    libdualcameraddm \
    libflash_pmic \
    libjpegdhw \
    libjpegdmahw \
    libjpegehw \
    libllvd_smore \
    libmmcamera2_c2d_module \
    libmmcamera2_cpp_module \
    libmmcamera2_dcrf \
    libmmcamera2_frame_algorithm \
    libmmcamera2_iface_modules \
    libmmcamera2_imglib_modules \
    libmmcamera2_is \
    libmmcamera2_isp_modules \
    libmmcamera2_mct \
    libmmcamera2_mct_shimlayer \
    libmmcamera2_pp_buf_mgr \
    libmmcamera2_pproc_modules \
    libmmcamera2_q3a_core \
    libmmcamera2_sensor_modules \
    libmmcamera2_stats_algorithm \
    libmmcamera2_stats_modules \
    libmmcamera_chromaflash_lib \
    libmmcamera_csidtg \
    libmmcamera_dbg \
    libmmcamera_dcrf_lib \
    libmmcamera_dummyalgo \
    libmmcamera_eebinparse \
    libmmcamera_eeprom_util \
    libmmcamera_eztune_module \
    libmmcamera_facedetection_lib \
    libmmcamera_faceproc \
    libmmcamera_faceproc2 \
    libmmcamera_hdr_gb_lib \
    libmmcamera_imglib \
    libmmcamera_isp_abf40 \
    libmmcamera_isp_bcc40 \
    libmmcamera_isp_be_stats44 \
    libmmcamera_isp_bf_stats47 \
    libmmcamera_isp_bg_stats44 \
    libmmcamera_isp_bhist_stats44 \
    libmmcamera_isp_bpc40 \
    libmmcamera_isp_chroma_enhan40 \
    libmmcamera_isp_chroma_suppress40 \
    libmmcamera_isp_clamp_encoder40 \
    libmmcamera_isp_clamp_video40 \
    libmmcamera_isp_clamp_viewfinder40 \
    libmmcamera_isp_color_correct40 \
    libmmcamera_isp_color_xform_encoder40 \
    libmmcamera_isp_color_xform_viewfinder40 \
    libmmcamera_isp_cs_stats44 \
    libmmcamera_isp_demosaic40 \
    libmmcamera_isp_demux40 \
    libmmcamera_isp_fovcrop_encoder40 \
    libmmcamera_isp_fovcrop_viewfinder40 \
    libmmcamera_isp_gamma40 \
    libmmcamera_isp_ihist_stats44 \
    libmmcamera_isp_linearization40 \
    libmmcamera_isp_ltm44 \
    libmmcamera_isp_luma_adaptation40 \
    libmmcamera_isp_mce40 \
    libmmcamera_isp_mesh_rolloff40 \
    libmmcamera_isp_rs_stats44 \
    libmmcamera_isp_scaler_encoder44 \
    libmmcamera_isp_scaler_viewfinder44 \
    libmmcamera_isp_sce40 \
    libmmcamera_isp_sub_module \
    libmmcamera_isp_template \
    libmmcamera_isp_wb40 \
    libmmcamera_llvd \
    libmmcamera_optizoom_lib \
    libmmcamera_paaf_lib \
    libmmcamera_pdaf \
    libmmcamera_pdafcamif \
    libmmcamera_ppbase_module \
    libmmcamera_quadracfa \
    libmmcamera_sakura_imx486_ofilm \
    libmmcamera_sakura_imx486_ofilm_eeprom \
    libmmcamera_sakura_ov12a10_sunny \
    libmmcamera_sakura_ov12a10_sunny_eeprom \
    libmmcamera_sakura_ov5675_ofilm \
    libmmcamera_sakura_ov5675_ofilm_eeprom \
    libmmcamera_sakura_ov5675_qtech \
    libmmcamera_sakura_ov5675_qtech_eeprom \
    libmmcamera_sakura_s5k5e8_ofilm \
    libmmcamera_sakura_s5k5e8_ofilm_eeprom \
    libmmcamera_sakura_s5k5e8_sunny \
    libmmcamera_sakura_s5k5e8_sunny_eeprom \
    libmmcamera_stillmore_lib \
    libmmcamera_sw2d_lib \
    libmmcamera_thread_services \
    libmmcamera_tintless_algo \
    libmmcamera_tintless_bg_pca_algo \
    libmmcamera_tuning \
    libmmcamera_tuning_lookup \
    libmmcamera_ubifocus_lib \
    libmmjpeg \
    libmmqjpeg_codec \
    libmmqjpegdma \
    libmpbase \
    libois_lc898122 \
    liboptizoom \
    libqomx_jpegdec \
    libqomx_jpegenc \
    libqomx_jpegenc_pipe \
    libremosaic_daemon \
    libseemore \
    libubifocus \
    libvideoutils \
    libvidhance \
    android.hardware.gatekeeper@1.0-impl-qti \
    android.hardware.keymaster@3.0-impl-qti \
    consumerir.msm8953 \
    fingerprint.fpc.default \
    gf_fingerprint.goodix.default \
    libgf_ca \
    libgf_hal \
    libkeymasterdeviceutils \
    libkeymasterprovision \
    libkeymasterutils \
    libvendor.goodix.hardware.fingerprint@1.0-service \
    android.hardware.gatekeeper@1.0-service-qti \
    android.hardware.keymaster@3.0-service-qti \
    mm-qcamera-daemon
